---
title: "Level1"
author: "Sridhar"
date: "1 January 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Add Libraries
```{r}
library(ggplot2)
library(dplyr)

```

## Analysis of Pokemon Data

There are various types of pokemon in that universe.Lets enter the world of pokemons!


```{r}
poke <- read.csv("Pokemon.csv")
head(poke)
```

## Investigating the Dataset

```{r}
str(poke)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Visualize 

```{r}
qplot( x = poke$Type.1,data = poke,xlab = "Types of Pokemons",ylab = "Count for each type",color = I('black'),fill = I("#5900b3"))
```



## Exploring Attacks

```{r}
ggplot(aes(x =Attack), data = poke)+
  geom_freqpoly(aes(color = Type.1))

```
## Best pokemon 

```{r}
str(poke$Total)
best_set <- subset(poke,Total >=700)
ggplot(aes(x = Name, y = Attack),data = best_set)+
  scale_x_discrete(limits = c(0,100))
```

